# Generated by Django 4.1.5 on 2023-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('image', models.ImageField(max_length=200, upload_to='category', verbose_name='Kategori Resmi')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(max_length=200, upload_to='category', verbose_name='Kart Resmi')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('isactive', models.BooleanField(verbose_name='Aktif Kart')),
                ('date_now', models.DateField(verbose_name='Tarih')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
            ],
        ),
    ]
