# Generated by Django 4.1.5 on 2023-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Yeni Ürün'),
        ),
    ]
